goodpoint/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers

from stores.views import StoreView, SaleView, StoreViewSet, SuperpromocionesView

router = routers.DefaultRouter()
router.register(r'store', StoreViewSet)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', StoreView.as_view(), name='index'),
    url(r'^store/new', StoreView.as_view(), name='create_store'),
    url(r'^sale/new', SaleView.as_view(), name='create_sale'),
    url(r'^obtener_promociones/', SuperpromocionesView.as_view(), name='obtener_promociones'),
    url(r'^api-auth/', include('rest_framework.urls')),
    url(r'^service/', include(router.urls)),
]
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stores/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class BaseModel(models.Model):
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

    class Meta:
        ordering=('-created_at',)




class Store(BaseModel):
    nombre=models.CharField(max_length=500)
    logo=models.ImageField(null=True)
    correo=models.EmailField()
    telefono=models.CharField(max_length=20)
    facebook=models.URLField(null=True)
    twitter=models.URLField(null=True)
    direccion=models.CharField(max_length=500)
    latitud=models.DecimalField(max_digits=20, decimal_places=16)
    longitud=models.DecimalField(max_digits=20, decimal_places=16)

    def __str__(self):
        return self.nombre
class Sale(BaseModel):
    encabazado=models.CharField(max_length=5000)
    fecha_inicio=models.DateTimeField()
    fecha_fin=models.DateTimeField()
    foto=models.ImageField(null=True)
    descripcion=models.TextField(null=True)
    tienda=models.ForeignKey(Store)

    def __str__(self):
        return self.encabazado
# class SaleStore(BaseModel):
#     descripcion=models.TextField()
#     encabazado = models.CharField(max_length=500)
#     fecha_inicio = models.DateTimeField()
#     fecha_fin = models.DateTimeField()
#     nombreTienda=models.ForeignKey(Store, on_delete=models.CASCADE)
#     latitud=
#     longitud=
#     foto=

stores/forms.py
from django.forms import *

from stores.models import Store, Sale


class StoreForm(ModelForm):
    class Meta:
        model=Store
        fields='__all__'

    nombre=CharField(required=True, widget=TextInput(attrs={'class': 'form-control'}))
    correo=EmailField(required=True, widget=EmailInput(attrs={'class': 'form-control'}))
    telefono=CharField(required=True, widget=TextInput(attrs={'class': 'form-control'}))
    facebook=CharField(required=True, widget=TextInput(attrs={'class': 'form-control'}))
    twitter=CharField(required=True, widget=TextInput(attrs={'class': 'form-control'}))
    direccion=CharField(required=True, widget=TextInput(attrs={'class': 'form-control'}))
    latitud=DecimalField(required=True, widget=NumberInput(attrs={'class': 'form-control', 'step':0.00000000000000000001}))
    longitud=DecimalField(required=True, widget=NumberInput(attrs={'class': 'form-control', 'step':0.00000000000000000001}))



class SaleForm(ModelForm):
    class Meta:
        model=Sale
        fields='__all__'

    encabazado=CharField(required=True, widget=TextInput(attrs={'class': 'form-control'}))
    fecha_inicio= DateTimeField(
        input_formats=['%Y-%m-%d %H:%M'],
        widget=DateTimeInput(attrs={
            'class': 'form-control',
        })
    )
    fecha_fin=DateTimeField(
        input_formats=['%Y-%m-%d %H:%M'],
        widget=DateTimeInput(attrs={
            'class': 'form-control',
        })
    )
    descripcion=CharField(required=True, widget=Textarea(attrs={'class':'form-control', 'rows': '3'}))
    tienda=ModelChoiceField(required=True, widget=Select(attrs={'class': 'form-control'}), queryset=Store.objects.all())

stores/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import datetime
import json
import math
from decimal import Decimal

from django.contrib import messages
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from django.shortcuts import render

# Create your views here.
from django.urls import reverse, reverse_lazy
from django.views.generic import FormView, CreateView
from django.views.generic.base import View
from rest_framework.viewsets import ViewSet, ModelViewSet

from stores.forms import StoreForm, SaleForm
from stores.models import Store, Sale
from stores.serializers import StoreSerializer


class StoreView(CreateView):
    template_name= 'store.html'
    form_class = StoreForm
    success_url = reverse_lazy('create_store')
    def form_valid(self, form):
        super(StoreView, self).form_valid(form)
        messages.success(request=self.request, message='La tienda se ha registrado correctamente.')
        return HttpResponseRedirect(self.get_success_url())

class SaleView(CreateView):
    template_name= 'sale.html'
    form_class = SaleForm
    success_url = reverse_lazy('create_sale')
    def form_valid(self, form):
        super(SaleView, self).form_valid(form)
        messages.success(request=self.request, message='La promoción ha sido registrada correctamente.')
        return HttpResponseRedirect(self.get_success_url())

class StoreViewSet(ModelViewSet):
    queryset = Store.objects.all()
    serializer_class = StoreSerializer

class SuperpromocionesView(View):
    distance=0.0075

    def get(self, *args, **kwargs):
        latitud=Decimal(self.request.GET['latitud'])
        longitud=Decimal(self.request.GET['longitud'])
        sales=Sale.objects.all()
        superpromocion=list()
        for s in sales:
            distancia= math.sqrt(math.pow(latitud - s.tienda.latitud, 2)+math.pow(longitud-s.tienda.longitud, 2))
            if distancia<self.distance:
                # crear json superpromoción
                from django.utils import timezone
                now = timezone.now()
                if s.fecha_inicio < now and now < s.fecha_fin:
                    superpromocion.append({
                        'id':s.id,
                        'descripcion':s.descripcion,
                        'encabezado':s.encabazado,
                        'fecha_inicio':s.fecha_inicio,
                        'fecha_fin':s.fecha_fin,
                        'latitud':float(s.tienda.latitud),
                        'longitud':float(s.tienda.longitud),
                        'nombretienda':s.tienda.nombre,
                        'foto':s.foto.url,
                    })
        dumps=json.dumps(superpromocion, default=myconverter)
        return HttpResponse(dumps)

def decimal_default(obj):
    if isinstance(obj, Decimal):
        return float(obj)
    raise TypeError

def myconverter(o):
    if isinstance(o, datetime.datetime):
        return o.__str__()
    return o

stores/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}GOODPOINT{% endblock title %}</title>
    {% block styles %}
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" >
        <link rel="stylesheet" href="{% static 'css/main.css' %}" >
        <link href="{% static 'css/bootstrap-datetimepicker.css' %}" rel="stylesheet">
        <link rel="stylesheet" href="{%  static 'css/fontawesome.css' %}">
        <link rel="stylesheet" href="{%  static 'css/all.css' %}">
    {% endblock styles %}
</head>
<body>
<div class="container-fluid">

{% block banner %}
    <div class="row">
        <div class="col-12 banner">
            <h1 class="text-center font-weight-bold align-middle"> GOODPOINT <img src="{% static 'images/logo.png' %}" width="45"></h1>
        </div>
    </div>
{% endblock banner %}
</div>
<div class="container-fluid">
{% block content %} AQUI VA EL CONTENIDO {% endblock content %}
</div>


<div class="row">
    <div class="col-md-12 footer">
        <p class="text-center">Creado por: <span style="font-weight: bold">Daniela Hernandez</span></p>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="{% static 'js/bootstrap-datetimepicker.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}" ></script>
<script src="{% static 'js/all.min.js' %}" data-auto-replace-svg ></script>
<script src="{% static 'main.js' %}"></script>
{% block scripts %}{% endblock %}
</body>
</html>

stores/templates/sale.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}Registrar promoción{% endblock title %}
{% block content %}
    <div class="row">
        <div class="col-md-offset-3 col-md-6 m-auto pt-2 pb-2">
            <div style="border: solid 1px #e8e8e8;  border-radius: 15px">
                <div class="p-2" style="background-color: #e8e8e8; border-radius: 15px 15px 0px 0px;">
                    <h2 class="text-center font-weight-bold">Registrar promoción</h2>
                </div>
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-success" role="alert">
                          {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
                <div style="margin: 20px">
                    <form action="" method="post" enctype="multipart/form-data" >
                        {% csrf_token %}
                        <div class="table-responsive">
                            <table class="table table-borderless table-condensed">
                                <tbody>
                                <tr>
                                    <td>Encabezado</td>
                                    <td>{{ form.encabazado }}
                                        {{ form.encabezado.errors }}</td>
                                </tr>
                                <tr>
                                    <td>Fecha de inicio</td>
                                    <td class="">
                                        {{ form.fecha_inicio }}
                                        {{ form.fecha_inicio.errors }}
                                    </td>
                                </tr>
                                <tr>
                                    <td>Fecha final</td>
                                    <td>
                                        {{ form.fecha_fin }}
                                        {{ form.fecha_fin.errors }}
                                    </td>
                                </tr>
                                <tr>
                                    <td>Imagen</td>
                                    <td>{{ form.foto }}
                                        {{ forms.foto.errors }}</td>
                                </tr>
                                <tr>
                                    <td>Descripción</td>
                                    <td>{{ form.descripcion }}
                                        {{ forms.descripcion.errors }}</td>
                                </tr>
                                <tr>
                                    <td>Tienda</td>
                                    <td>{{ form.tienda }}
                                        {{ forms.tienda.errors }}</td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                        <br>
                            <button type="submit" value="guardar" class="btn btn-primary btn-block"><i class="fa fa-save"></i> Guardar</button>
                    </form>
                    <br>
                    <p class="text-center">Para registrar tienda presione click <span><a href="{% url 'create_store' %}">aquí</a></span></p>
                </div>
            </div>
        </div>
    </div>


{% endblock content %}
{% block scripts %}
    <script>
        $(function () {
                $('#id_fecha_inicio').datetimepicker();
            });
        $(function () {
                $('#id_fecha_fin').datetimepicker();
            });
    </script>
{% endblock scripts %}

stores/templates/store.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}Registrar tienda{% endblock title %}
{% block content %}
    <div class="row">
        <div class="col-md-offset-3 col-md-6 m-auto pt-2 pb-2">
            <div style="border: solid 1px #e8e8e8;  border-radius: 15px">
                <div class="p-2" style="background-color: #e8e8e8; border-radius: 15px 15px 0px 0px;">
                    <h2 class="text-center font-weight-bold">Registrar tienda</h2>
                </div>
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-success" role="alert">
                          {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
                <div style="margin: 20px">
                 <form action="" method="post" enctype="multipart/form-data" >
                        {% csrf_token %}
                     <div class="table-responsive">
                         <table class="table table-borderless table-condensed">
                             <tbody>
                             <tr>
                                 <td>Nombre</td>
                                 <td>{{ form.nombre }}</td>
                             </tr>
                             <tr>
                                 <td>Logo</td>
                                 <td>{{ form.logo }}</td>
                             </tr>
                             <tr>
                                 <td>Correo</td>
                                 <td>{{ form.correo }}</td>
                             </tr>
                             <tr>
                                 <td>Teléfono</td>
                                 <td>{{ form.telefono }}</td>
                             </tr>
                             <tr>
                                 <td>Facebook</td>
                                 <td>{{ form.facebook }}</td>
                             </tr>
                             <tr>
                                 <td>Twitter</td>
                                 <td>{{ form.twitter }}</td>
                             </tr>
                             <tr>
                                 <td>Direccion</td>
                                 <td>{{ form.direccion }}</td>
                             </tr>
                             <tr>
                                 <td>Latitud</td>
                                 <td>{{ form.latitud }}</td>
                             </tr>
                             <tr>
                                 <td>Longitud</td>
                                 <td>{{ form.longitud }}</td>
                             </tr>
                             </tbody>
                         </table>
                     </div>
                     <p class="text-center">Para obetener las coordenadas use
                        <a href="http://www.bufa.es/google-maps-latitud-longitud/" target="_blank">bufa</a>
                    </p>
                 <br>
                            <button type="submit" value="guardar" class="btn btn-primary btn-block"><i class="fa fa-save"></i> Guardar</button>
                    </form>
                    <br>
                    <p class="text-center">Para registrar promoción presione click <span><a href="{% url 'create_sale' %}">aquí</a></span></p>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}